# Autogenerated wrapper script for JonkerVolgenant_jll for x86_64-apple-darwin
export bipartite_assignement

JLLWrappers.@generate_wrapper_header("JonkerVolgenant")
JLLWrappers.@declare_library_product(bipartite_assignement, "@rpath/bipartite_assignement.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        bipartite_assignement,
        "lib/bipartite_assignement.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
