# Autogenerated wrapper script for JonkerVolgenant_jll for x86_64-w64-mingw32
export bipartite_assignement

JLLWrappers.@generate_wrapper_header("JonkerVolgenant")
JLLWrappers.@declare_library_product(bipartite_assignement, "bipartite_assignement.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        bipartite_assignement,
        "bin\\bipartite_assignement.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
